/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/device/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * First-boot registration of a device.
         * @description Called once by the firmware right after WiFi credentials have been
         *     provisioned via BLE. The device proves possession of its baked-in
         *     per-device secret via HMAC and receives a device-scoped token plus
         *     the initial sync payload.
         */
        post: operations["registerDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/device/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pull configuration, card bindings and audio manifest.
         * @description Devices poll this endpoint roughly every 10 minutes (configurable from
         *     the dashboard). The response is the **complete current state**: cards,
         *     audio items with presigned URLs, power-saving thresholds and feature
         *     flags. Clients diff against their cached version.
         */
        get: operations["syncDevice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/device/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push a batch of events from the device.
         * @description Devices buffer events (card scans, button presses, errors) locally and
         *     flush them in batches. The endpoint is idempotent on `eventId`.
         */
        post: operations["postDeviceEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new user account. */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange email + password for an access/refresh token pair. */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trade a refresh token for a new access/refresh pair. */
        post: operations["refreshTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's profile. */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List devices owned by the authenticated user. */
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        /** Get a single device. */
        get: operations["getDevice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim an unclaimed device.
         * @description After BLE pairing the user owns the device. The claim step transfers
         *     ownership in the backend. The body carries a short-lived claim code
         *     displayed on the dashboard / printed on the box.
         */
        post: operations["claimDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{id}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        /** List card bindings on a device. */
        get: operations["listDeviceCards"];
        put?: never;
        /** Bind an RFID card UID to an audio item on a device. */
        post: operations["bindCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{id}/cards/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
                /** @description RFID UID in lowercase hex (no separators). */
                uid: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a card binding from a device. */
        delete: operations["unbindCard"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audio items owned by the authenticated user. */
        get: operations["listAudio"];
        put?: never;
        /**
         * Create an audio item and obtain a presigned upload URL.
         * @description The backend never proxies audio bytes. The client uploads the raw file
         *     directly to object storage using the returned presigned URL, then
         *     calls `POST /v1/audio/{id}/finalize` to trigger transcoding.
         */
        post: operations["createAudio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get an audio item. */
        get: operations["getAudio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio/{id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Notify the backend that the raw upload is complete.
         * @description Triggers ffmpeg transcoding (MP3 128 kbps CBR mono 44.1 kHz). The item
         *     moves to `state: processing` until the worker is done; consumers
         *     should poll `GET /v1/audio/{id}` or rely on the next device sync.
         */
        post: operations["finalizeAudio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
            /** @description SemVer of the backend build. */
            version: string;
            /** @description Git commit short SHA. */
            commit?: string;
        };
        Error: {
            /**
             * @description Machine-readable error code (snake_case, stable).
             * @example invalid_credentials
             * @example device_already_claimed
             * @example validation_failed
             */
            code: string;
            /** @description Human-readable explanation. */
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        AuthTokens: {
            /** @description JWT access token. Short-lived (15 min). */
            accessToken: string;
            /** @description Refresh token. Single-use; rotated on every refresh. */
            refreshToken: string;
            /** @description Access-token TTL in seconds. */
            expiresIn: number;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        UserRegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            displayName?: string;
        };
        UserLoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName?: string;
            /** Format: date-time */
            createdAt: string;
        };
        Device: {
            /** Format: uuid */
            id: string;
            /** @description Per-unit serial printed on the device. */
            serial: string;
            /**
             * Format: uuid
             * @description User who claimed the device. Null while unclaimed.
             */
            ownerId?: string;
            /** @description User-chosen device name (e.g. "Marta's box"). */
            name?: string;
            /** @enum {string} */
            state: "unclaimed" | "claimed" | "retired";
            firmwareVersion?: string;
            /** Format: date-time */
            lastSeenAt?: string;
            /** Format: date-time */
            createdAt: string;
        };
        DeviceList: {
            items: components["schemas"]["Device"][];
            nextCursor?: string;
        };
        DeviceRegisterRequest: {
            serial: string;
            firmwareVersion: string;
            /** @description BLE MAC address, lowercase hex with colons. */
            macAddress?: string;
        };
        DeviceRegisterResponse: {
            device: components["schemas"]["Device"];
            /** @description Short-lived code shown to the user during pairing. */
            claimCode?: string;
        };
        DeviceClaimRequest: {
            claimCode: string;
            name?: string;
        };
        DeviceSyncResponse: {
            /** Format: date-time */
            serverTime: string;
            config: components["schemas"]["DeviceConfig"];
            cards: components["schemas"]["CardBinding"][];
            audio: components["schemas"]["AudioSyncEntry"][];
        };
        DeviceConfig: {
            /** @description Seconds of idle before LIGHT_SLEEP. Default 30. */
            lightSleepAfterSec: number;
            /** @description Seconds of idle before DEEP_SLEEP. Default 300. */
            deepSleepAfterSec: number;
            /** @description Hard ceiling for the volume encoder. */
            volumeMax: number;
            ledBrightness?: number;
        };
        DeviceEventsRequest: {
            events: components["schemas"]["DeviceEvent"][];
        };
        DeviceEvent: {
            /**
             * Format: uuid
             * @description Client-generated UUID; used for idempotency.
             */
            eventId: string;
            /** Format: date-time */
            ts: string;
            /** @enum {string} */
            type: "card_scanned" | "card_unknown" | "playback_started" | "playback_finished" | "button_pressed" | "low_battery" | "error";
            /** @description Free-form per-event data. Shapes will be tightened in phase 2. */
            payload?: {
                [key: string]: unknown;
            };
        };
        Audio: {
            /** Format: uuid */
            id: string;
            title: string;
            description?: string;
            durationMs?: number;
            /** @enum {string} */
            state: "uploading" | "processing" | "ready" | "failed";
            /** @description Hex SHA-256 of the transcoded MP3. */
            sha256?: string;
            sizeBytes?: number;
            /** Format: date-time */
            createdAt: string;
        };
        AudioCreateRequest: {
            title: string;
            description?: string;
            /**
             * @description MIME type of the source file the client will upload.
             * @example audio/mpeg
             * @example audio/wav
             * @example audio/x-m4a
             * @example audio/ogg
             */
            sourceContentType: string;
        };
        AudioCreateResponse: {
            audio: components["schemas"]["Audio"];
            upload: {
                /**
                 * Format: uri
                 * @description Presigned URL for the raw upload.
                 */
                url: string;
                /** @enum {string} */
                method: "PUT";
                /** Format: date-time */
                expiresAt: string;
                /** @description Headers the client must include verbatim. */
                headers?: {
                    [key: string]: string;
                };
            };
        };
        AudioList: {
            items: components["schemas"]["Audio"][];
            nextCursor?: string;
        };
        AudioSyncEntry: {
            /** Format: uuid */
            id: string;
            sha256: string;
            sizeBytes?: number;
            /**
             * Format: uri
             * @description Presigned GET URL valid until `expiresAt`.
             */
            downloadUrl: string;
            /** Format: date-time */
            expiresAt: string;
        };
        CardBinding: {
            /** @description RFID UID, lowercase hex, no separators. */
            uid: string;
            /** Format: uuid */
            audioId: string;
            /** Format: date-time */
            boundAt?: string;
        };
        CardBindingRequest: {
            uid: string;
            /** Format: uuid */
            audioId: string;
        };
        CardBindingList: {
            items: components["schemas"]["CardBinding"][];
        };
    };
    responses: {
        /** @description Missing or invalid authentication. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request body failed validation. */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Opaque pagination cursor returned by a previous response. */
        Cursor: string;
        /** @description Device identifier (UUID). */
        DeviceId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Service is degraded or unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    registerDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceRegisterRequest"];
            };
        };
        responses: {
            /** @description Device registered (idempotent). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRegisterResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Unprocessable"];
        };
    };
    syncDevice: {
        parameters: {
            query?: {
                /** @description ISO-8601 timestamp of the last successful sync. If omitted, a full snapshot is returned. */
                since?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current sync payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSyncResponse"];
                };
            };
            /** @description Nothing changed since `since`. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    postDeviceEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceEventsRequest"];
            };
        };
        responses: {
            /** @description Events accepted for processing. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Unprocessable"];
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegisterRequest"];
            };
        };
        responses: {
            /** @description User created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            /** @description Email already in use. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["Unprocessable"];
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLoginRequest"];
            };
        };
        responses: {
            /** @description Authentication successful. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    refreshTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description New token pair issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listDevices: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor returned by a previous response. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated device list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    claimDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceClaimRequest"];
            };
        };
        responses: {
            /** @description Device claimed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Device already claimed. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listDeviceCards: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bindings (unpaginated; capped server-side). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardBindingList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    bindCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardBindingRequest"];
            };
        };
        responses: {
            /** @description Card binding upserted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardBinding"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    unbindCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
                /** @description RFID UID in lowercase hex (no separators). */
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Binding removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listAudio: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor returned by a previous response. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createAudio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AudioCreateRequest"];
            };
        };
        responses: {
            /** @description Audio item created with upload URL. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioCreateResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Unprocessable"];
        };
    };
    getAudio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audio item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Audio"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    finalizeAudio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Finalization accepted; transcoding queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Audio"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Audio already finalized. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
