/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe with per-dependency checks.
         * @description Liveness (`/v1/health`) only proves the process answered. Readiness
         *     also checks that every downstream the API actually depends on (the
         *     database, object storage) is reachable. Orchestrators should use
         *     this endpoint to decide whether the instance should receive traffic.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/device/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * First-boot registration of a device.
         * @description Registers a new device and returns it in the `unclaimed` state together
         *     with a `claimCode` the user enters to claim it.
         *
         *     Two callers are accepted:
         *     - A **physical device** authenticating with `deviceHmac`. Called once by
         *       the firmware right after WiFi credentials have been provisioned via
         *       BLE; the device proves possession of its baked-in per-device secret via
         *       HMAC. The `virtual` field is ignored and treated as `false`.
         *     - A **user app acting as a virtual device** authenticating with
         *       `userJwt`. The app sends `virtual: true` to register itself as a
         *       software-only device for the authenticated user.
         *
         *     Idempotent on `serial`: re-registering an existing device returns the
         *     current record. `claimCode` is present only while the device is
         *     `unclaimed`.
         */
        post: operations["registerDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/device/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pull configuration, card bindings and audio manifest.
         * @description Devices poll this endpoint roughly every 10 minutes (configurable from
         *     the dashboard). The response is the **complete current state**: cards,
         *     audio items with presigned URLs, power-saving thresholds and feature
         *     flags. Clients diff against their cached version.
         *
         *     Two callers are accepted:
         *     - A **physical device** authenticating with `deviceHmac`; the device is
         *       resolved from the HMAC `keyId`.
         *     - A **user app acting as a device** authenticating with `userJwt`. In
         *       this case `device_id` is **required** and must reference a claimed
         *       device owned by the caller.
         */
        get: operations["syncDevice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/device/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push a batch of events from the device.
         * @description Devices buffer events (card scans, button presses, errors) locally and
         *     flush them in batches. The endpoint is idempotent on `eventId`.
         *
         *     Two callers are accepted:
         *     - A **physical device** authenticating with `deviceHmac`; the device is
         *       resolved from the HMAC `keyId`.
         *     - A **user app acting as a device** authenticating with `userJwt`. In
         *       this case `device_id` is **required** and must reference a claimed
         *       device owned by the caller.
         */
        post: operations["postDeviceEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user accounts (admin only).
         * @description Admin-only directory of every account. The caller must present a valid
         *     `admin` bearer token; an unauthenticated request gets `401` and an
         *     authenticated non-admin gets `403`.
         *
         *     Results are ordered newest-first and paginated by opaque cursor: pass
         *     the previous response's `nextCursor` back as the `cursor` query param to
         *     fetch the next page. A response without `nextCursor` is the last page.
         */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new end-user account (admin only).
         * @description Admin-only account creation. The caller must present a valid `admin`
         *     bearer token; the new account is **not** logged in and no tokens are
         *     issued — the response is the created user's profile. The caller's own
         *     session is unaffected.
         *
         *     There is no public self-registration. An unauthenticated request gets
         *     `401`; an authenticated non-admin gets `403`.
         *
         *     The optional `role` field lets an admin choose the new account's role
         *     (`admin` or `user`). When omitted it defaults to `user`. This is the
         *     only path to mint an `admin` from the dashboard; the bootstrap seed
         *     (`BOOTSTRAP_ADMIN_*`) remains for first-boot provisioning.
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange email + password for an access/refresh token pair. */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trade a refresh token for a new access/refresh pair. */
        post: operations["refreshTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's profile. */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the authenticated user's password.
         * @description Verifies `currentPassword`, then sets `newPassword`. All of the user's
         *     refresh tokens are revoked (logging out every other session) and a fresh
         *     access/refresh pair is issued for the caller, so the current session
         *     survives the change.
         */
        patch: operations["changePassword"];
        trace?: never;
    };
    "/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List devices owned by the authenticated user. */
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        /** Get a single device. */
        get: operations["getDevice"];
        put?: never;
        post?: never;
        /**
         * Retire (remove) a device owned by the authenticated user.
         * @description Soft-deletes the device: it transitions to `retired`, stops syncing
         *     and disappears from the owner's device list. Ownership is preserved so
         *     the action can be reversed by support — the hardware identity and its
         *     secret survive, the unit is never destroyed. Scoped to the caller: a
         *     device owned by another user (or already retired) responds `404`.
         */
        delete: operations["retireDevice"];
        options?: never;
        head?: never;
        /**
         * Update a device owned by the authenticated user.
         * @description Renames a claimed device. Only the user-chosen `name` is mutable; the
         *     serial, state and firmware version are owned by the device lifecycle
         *     and cannot be changed here. Scoped to the caller: a device owned by
         *     another user (or already retired) responds `404`, never `403`, so the
         *     endpoint does not leak which device ids exist.
         */
        patch: operations["updateDevice"];
        trace?: never;
    };
    "/v1/devices/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        /**
         * List events recorded for a device.
         * @description Returns the events the device has pushed via `POST /v1/device/events`
         *     (card scans, button presses, errors). The mobile app uses it with
         *     `type=card_unknown` to build the "cards to bind" list.
         *
         *     Scoped to the caller: a device owned by another user (or unknown)
         *     responds `404`, never `403`, so the endpoint does not leak which device
         *     ids exist. Results are ordered newest-first by `ts` and paginated by
         *     opaque cursor — pass the previous response's `nextCursor` back as the
         *     `cursor` query param. A response without `nextCursor` is the last page.
         */
        get: operations["listDeviceEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim an unclaimed device.
         * @description After BLE pairing the user owns the device. The claim step transfers
         *     ownership in the backend. The body carries a short-lived claim code
         *     displayed on the dashboard / printed on the box.
         */
        post: operations["claimDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{id}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        /** List card bindings on a device. */
        get: operations["listDeviceCards"];
        put?: never;
        /** Bind an RFID card UID to an audio item on a device. */
        post: operations["bindCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/{id}/cards/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
                /** @description RFID UID in lowercase hex (no separators). */
                uid: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a card binding from a device. */
        delete: operations["unbindCard"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audio items owned by the authenticated user. */
        get: operations["listAudio"];
        put?: never;
        /**
         * Create an audio item and obtain a presigned upload URL.
         * @description The backend never proxies audio bytes. The client uploads the raw file
         *     directly to object storage using the returned presigned URL, then
         *     calls `POST /v1/audio/{id}/finalize` to trigger transcoding.
         */
        post: operations["createAudio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get an audio item. */
        get: operations["getAudio"];
        put?: never;
        post?: never;
        /**
         * Delete an audio item.
         * @description Permanently removes the audio metadata and its stored objects (the raw
         *     upload and the transcoded MP3). Any card bindings that reference this
         *     audio are removed as well (cascade). Only the owner may delete their
         *     own audio; deleting another user's audio returns `404`.
         */
        delete: operations["deleteAudio"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio/{id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Notify the backend that the raw upload is complete.
         * @description Triggers ffmpeg transcoding (MP3 128 kbps CBR mono 44.1 kHz). The item
         *     moves to `state: processing` until the worker is done; consumers
         *     should poll `GET /v1/audio/{id}` or rely on the next device sync.
         */
        post: operations["finalizeAudio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/firmware/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the latest firmware manifest for a hardware revision.
         * @description Returns the manifest of the most recent firmware release published for
         *     the given hardware revision. Devices call this on boot and after each
         *     successful sync to know whether to upgrade. The `url` is a short-lived
         *     presigned GET URL pointing at the signed firmware binary; the device
         *     must verify `sha256` (integrity) and `signature` (authenticity) before
         *     flashing. The signature is over the raw binary bytes using Ed25519;
         *     the public key is baked into the running firmware image.
         */
        get: operations["getLatestFirmware"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * External service configuration status (admin only).
         * @description Read-only status of the external services the backend integrates with:
         *     email (Resend), audio object storage (S3 / MinIO / R2), log traces
         *     (BetterStack) and crash reporting (Sentry). For each service it reports
         *     whether it is configured, the **names** of the environment variables
         *     that drive it, and a handful of non-secret resolved hints (region,
         *     bucket, masked endpoint, …).
         *
         *     Configuration is operator-owned: values live in the backend's
         *     environment (`.env`) and are read at process start. This endpoint
         *     **never** returns a secret value — only whether each variable is set.
         *     To change a value, edit the environment and restart the backend.
         *
         *     Admin-only: an unauthenticated request gets `401` and an authenticated
         *     non-admin gets `403`.
         */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface webhooks {
    deviceOnline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A device transitioned to online.
         * @description Fired when the backend receives traffic from a device after at least
         *     5 minutes of silence — i.e. the device just came back online from a
         *     deep-sleep or network outage. The webhook is **not** fired on every
         *     heartbeat; only on edge transitions offline → online.
         *
         *     See [Webhook delivery](#section/Webhook-delivery) in the description
         *     for signature verification and retry semantics.
         */
        post: operations["deviceOnlineWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    audioFinalized: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Audio transcoding completed.
         * @description Fired when an audio item transitions out of `processing` — either to
         *     `ready` (transcode succeeded) or `failed` (transcode errored out).
         *     Use `data.audio.state` to disambiguate.
         */
        post: operations["audioFinalizedWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
            /** @description SemVer of the backend build. */
            version: string;
            /** @description Git commit short SHA. */
            commit?: string;
        };
        Ready: {
            /**
             * @description Aggregate readiness. `degraded` whenever any check is not `ok`.
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** @description Per-dependency check results, keyed by check name (`database`, `objectStorage`, …). */
            checks: {
                [key: string]: components["schemas"]["ReadyCheck"];
            };
        };
        ReadyCheck: {
            /** @enum {string} */
            status: "ok" | "error" | "timeout";
            /** @description Round-trip latency of the probe. Present on success. */
            latencyMs?: number;
            /** @description Short failure description. Present when `status` is not `ok`. */
            error?: string;
        };
        ConfigStatus: {
            /** @description One entry per external service the backend integrates with. */
            services: components["schemas"]["ServiceConfig"][];
        };
        ServiceConfig: {
            /**
             * @description Stable machine key for the service.
             * @enum {string}
             */
            service: "email" | "storage" | "traces" | "crash";
            /** @description Human-readable service name for the dashboard. */
            label: string;
            /** @description True when every `required` variable of this service is set. */
            configured: boolean;
            /** @description Environment variables that drive this service. */
            variables: components["schemas"]["ConfigVariable"][];
            /**
             * @description Non-secret resolved values that help an operator confirm which
             *     environment is loaded (region, bucket, masked endpoint, …). Never
             *     contains a secret value.
             */
            hints?: {
                [key: string]: string;
            };
        };
        ConfigVariable: {
            /** @description Environment variable name, e.g. `RESEND_API_KEY`. */
            name: string;
            /** @description Whether the variable is present and non-empty. The value itself is never returned. */
            set: boolean;
            /** @description Whether the value is sensitive. Secret values are never exposed, set or not. */
            secret: boolean;
            /** @description Whether this variable counts toward the service's `configured` flag. */
            required: boolean;
        };
        Error: {
            /**
             * @description Machine-readable error code (snake_case, stable).
             * @example invalid_credentials
             * @example device_already_claimed
             * @example validation_failed
             */
            code: string;
            /** @description Human-readable explanation. */
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        AuthTokens: {
            /** @description JWT access token. Short-lived (15 min). */
            accessToken: string;
            /** @description Refresh token. Single-use; rotated on every refresh. */
            refreshToken: string;
            /** @description Access-token TTL in seconds. */
            expiresIn: number;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        UserRegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            displayName?: string;
            /**
             * @description Role for the new account. Optional; defaults to `user` when omitted.
             *     Only an admin caller can reach this endpoint, so this is the path to
             *     create another `admin` from the dashboard.
             * @default user
             * @enum {string}
             */
            role: "admin" | "user";
        };
        UserLoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        ChangePasswordRequest: {
            /** Format: password */
            currentPassword: string;
            /** Format: password */
            newPassword: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName?: string;
            /**
             * @description Authorization role. `user` is an ordinary end-user scoped to their
             *     own resources; `admin` has global privileges. New accounts default
             *     to `user` unless an admin explicitly creates an `admin`.
             * @enum {string}
             */
            role: "admin" | "user";
            /** Format: date-time */
            createdAt: string;
        };
        UserList: {
            items: components["schemas"]["User"][];
            nextCursor?: string;
        };
        Device: {
            /** Format: uuid */
            id: string;
            /** @description Per-unit serial printed on the device. */
            serial: string;
            /**
             * Format: uuid
             * @description User who claimed the device. Null while unclaimed.
             */
            ownerId?: string;
            /** @description User-chosen device name (e.g. "Marta's box"). */
            name?: string;
            /** @enum {string} */
            state: "unclaimed" | "claimed" | "retired";
            firmwareVersion?: string;
            /** Format: date-time */
            lastSeenAt?: string;
            /** Format: date-time */
            createdAt: string;
        };
        DeviceList: {
            items: components["schemas"]["Device"][];
            nextCursor?: string;
        };
        DeviceRegisterRequest: {
            serial: string;
            firmwareVersion: string;
            /** @description BLE MAC address, lowercase hex with colons. */
            macAddress?: string;
            /**
             * @description Whether this is a software-only device registered by a user app via
             *     `userJwt`. Ignored (treated as `false`) for `deviceHmac` callers.
             * @default false
             */
            virtual: boolean;
        };
        DeviceRegisterResponse: {
            device: components["schemas"]["Device"];
            /**
             * @description Short-lived code shown to the user during pairing. Present only while
             *     `device.state` is `unclaimed`; omitted once the device is claimed.
             */
            claimCode?: string;
        };
        DeviceClaimRequest: {
            claimCode: string;
            name?: string;
        };
        /**
         * @description Mutable device fields. Only the user-chosen name can be changed;
         *     serial, state and firmware are managed by the device lifecycle.
         */
        DeviceUpdateRequest: {
            /** @description New device name. Send null to clear it. */
            name?: string | null;
        };
        DeviceSyncResponse: {
            /** Format: date-time */
            serverTime: string;
            config: components["schemas"]["DeviceConfig"];
            cards: components["schemas"]["CardBinding"][];
            audio: components["schemas"]["AudioSyncEntry"][];
        };
        DeviceConfig: {
            /** @description Seconds of idle before LIGHT_SLEEP. Default 30. */
            lightSleepAfterSec: number;
            /** @description Seconds of idle before DEEP_SLEEP. Default 300. */
            deepSleepAfterSec: number;
            /** @description Hard ceiling for the volume encoder. */
            volumeMax: number;
            ledBrightness?: number;
        };
        DeviceEventsRequest: {
            events: components["schemas"]["DeviceEvent"][];
        };
        DeviceEventList: {
            items: components["schemas"]["DeviceEvent"][];
            nextCursor?: string;
        };
        /**
         * @description A single event emitted by the firmware. The wire shape is a
         *     discriminated union keyed by `type`; consumers should pattern-match on
         *     it (codegen libraries surface this as a sum type / tagged enum).
         *
         *     `eventId` is a client-generated UUID used for idempotency; the backend
         *     deduplicates on `(deviceId, eventId)`.
         */
        DeviceEvent: components["schemas"]["DeviceEventCardScanned"] | components["schemas"]["DeviceEventCardUnknown"] | components["schemas"]["DeviceEventPlaybackStarted"] | components["schemas"]["DeviceEventPlaybackFinished"] | components["schemas"]["DeviceEventButtonPressed"] | components["schemas"]["DeviceEventVolumeChanged"] | components["schemas"]["DeviceEventLowBattery"] | components["schemas"]["DeviceEventWifiSignal"] | components["schemas"]["DeviceEventError"];
        DeviceEventBase: {
            /**
             * Format: uuid
             * @description Client-generated UUID; used for idempotency.
             */
            eventId: string;
            /** Format: date-time */
            ts: string;
            type: string;
        };
        DeviceEventCardScanned: components["schemas"]["DeviceEventBase"] & {
            /** @constant */
            type: "card_scanned";
            payload: {
                /** @description RFID UID, lowercase hex, no separators. */
                uid: string;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "card_scanned";
        };
        DeviceEventCardUnknown: components["schemas"]["DeviceEventBase"] & {
            /** @constant */
            type: "card_unknown";
            payload: {
                uid: string;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "card_unknown";
        };
        DeviceEventPlaybackStarted: components["schemas"]["DeviceEventBase"] & {
            /** @constant */
            type: "playback_started";
            payload: {
                /** Format: uuid */
                audioId: string;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "playback_started";
        };
        DeviceEventPlaybackFinished: components["schemas"]["DeviceEventBase"] & {
            /** @constant */
            type: "playback_finished";
            payload: {
                /** Format: uuid */
                audioId: string;
                /**
                 * @description `completed` — playback reached the end.
                 *     `interrupted` — a new card was scanned mid-playback, or the user pressed pause.
                 *     `error` — the decoder failed; a paired `error` event follows.
                 * @enum {string}
                 */
                reason: "completed" | "interrupted" | "error";
                /** @description Position at which playback ended. Useful when `reason` is `interrupted`. */
                positionMs?: number;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "playback_finished";
        };
        DeviceEventButtonPressed: components["schemas"]["DeviceEventBase"] & {
            /** @constant */
            type: "button_pressed";
            payload: {
                /**
                 * @description Which physical control fired the event.
                 * @enum {string}
                 */
                button: "reset" | "pairing" | "encoder";
                /** @description How long the button was held. Omitted for momentary taps. */
                durationMs?: number;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "button_pressed";
        };
        DeviceEventVolumeChanged: components["schemas"]["DeviceEventBase"] & {
            /** @constant */
            type: "volume_changed";
            payload: {
                /** @description Volume level after the change. */
                volume: number;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "volume_changed";
        };
        DeviceEventLowBattery: components["schemas"]["DeviceEventBase"] & {
            /** @constant */
            type: "low_battery";
            payload: {
                batteryPercent: number;
                /** @description Pack voltage in millivolts. Optional, useful for debugging. */
                voltageMv?: number;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "low_battery";
        };
        DeviceEventWifiSignal: components["schemas"]["DeviceEventBase"] & {
            /** @constant */
            type: "wifi_signal";
            payload: {
                /** @description RSSI in dBm. Closer to 0 is better. */
                rssi: number;
                /** @description SSID the device is currently associated with. */
                ssid?: string;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "wifi_signal";
        };
        DeviceEventError: components["schemas"]["DeviceEventBase"] & {
            /** @constant */
            type: "error";
            payload: {
                /** @description Short, snake_case error tag (e.g. `audio_not_in_sync`, `decoder_failed`). */
                reason: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
        };
        Audio: {
            /** Format: uuid */
            id: string;
            title: string;
            description?: string;
            durationMs?: number;
            /** @enum {string} */
            state: "uploading" | "processing" | "ready" | "failed";
            /** @description Hex SHA-256 of the transcoded MP3. */
            sha256?: string;
            sizeBytes?: number;
            /** Format: date-time */
            createdAt: string;
        };
        AudioCreateRequest: {
            title: string;
            description?: string;
            /**
             * @description MIME type of the source file the client will upload.
             * @example audio/mpeg
             * @example audio/wav
             * @example audio/x-m4a
             * @example audio/ogg
             */
            sourceContentType: string;
        };
        AudioCreateResponse: {
            audio: components["schemas"]["Audio"];
            upload: {
                /**
                 * Format: uri
                 * @description Presigned URL for the raw upload.
                 */
                url: string;
                /** @enum {string} */
                method: "PUT";
                /** Format: date-time */
                expiresAt: string;
                /** @description Headers the client must include verbatim. */
                headers?: {
                    [key: string]: string;
                };
            };
        };
        AudioList: {
            items: components["schemas"]["Audio"][];
            nextCursor?: string;
        };
        AudioSyncEntry: {
            /** Format: uuid */
            id: string;
            sha256: string;
            sizeBytes?: number;
            /**
             * Format: uri
             * @description Presigned GET URL valid until `expiresAt`.
             */
            downloadUrl: string;
            /** Format: date-time */
            expiresAt: string;
        };
        CardBinding: {
            /** @description RFID UID, lowercase hex, no separators. */
            uid: string;
            /** Format: uuid */
            audioId: string;
            /** Format: date-time */
            boundAt?: string;
        };
        CardBindingRequest: {
            uid: string;
            /** Format: uuid */
            audioId: string;
        };
        CardBindingList: {
            items: components["schemas"]["CardBinding"][];
        };
        FirmwareManifest: {
            /**
             * @description SemVer of the firmware release.
             * @example 0.2.0
             * @example 1.0.0
             */
            version: string;
            /** @description Hardware revision this build targets. */
            hwRev: string;
            /**
             * Format: uri
             * @description Presigned GET URL for the signed firmware binary.
             */
            url: string;
            /**
             * Format: date-time
             * @description When the presigned URL stops being valid.
             */
            expiresAt: string;
            /** @description Lowercase hex SHA-256 of the binary. */
            sha256: string;
            /**
             * @description Lowercase hex Ed25519 signature of the binary, computed offline by
             *     the maintainer with the firmware-signing private key. The matching
             *     public key is baked into the running firmware image.
             */
            signature: string;
            /** @enum {string} */
            signatureAlgorithm: "ed25519";
            sizeBytes: number;
            /** Format: date-time */
            releasedAt: string;
            /** @description Optional human-readable release notes. */
            notes?: string;
        };
        WebhookEnvelopeBase: {
            /**
             * Format: uuid
             * @description Logical event id. Distinct from `Hush-Webhook-Id`: the header
             *     changes on every retry, while this one stays stable so consumers
             *     can deduplicate cross-retry.
             */
            id: string;
            /** @description Event type. Always mirrors the `Hush-Webhook-Type` header. */
            type: string;
            /**
             * Format: date-time
             * @description When the event happened on the server (UTC, with `Z` suffix).
             */
            occurredAt: string;
        };
        WebhookEnvelopeDeviceOnline: components["schemas"]["WebhookEnvelopeBase"] & {
            /** @constant */
            type: "device.online";
            data: components["schemas"]["WebhookDeviceOnlineData"];
        };
        WebhookDeviceOnlineData: {
            device: components["schemas"]["Device"];
            /**
             * @description How long the device was silent before this transition. Always at
             *     least 300 (5 minutes — the threshold that defines "back online").
             */
            previouslyOfflineSec: number;
        };
        WebhookEnvelopeAudioFinalized: components["schemas"]["WebhookEnvelopeBase"] & {
            /** @constant */
            type: "audio.finalized";
            data: components["schemas"]["WebhookAudioFinalizedData"];
        };
        WebhookAudioFinalizedData: {
            audio: components["schemas"]["Audio"];
            /**
             * @description Short error tag, present iff `audio.state == failed`. Examples:
             *     `transcode_failed`, `unsupported_codec`, `source_missing`.
             */
            failureReason?: string;
        };
    };
    responses: {
        /** @description Missing or invalid authentication. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request is malformed or missing a required parameter. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request body failed validation. */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The client has exceeded the rate limit for this route. The response
         *     always carries a `Retry-After` header (seconds) and the standard
         *     `X-RateLimit-*` triplet so clients can self-throttle.
         */
        TooManyRequests: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Opaque pagination cursor returned by a previous response. */
        Cursor: string;
        /** @description Device identifier (UUID). */
        DeviceId: string;
        /**
         * @description HMAC-SHA256 signature of `<t>.<raw-body>` using the per-user webhook
         *     secret. Format `t=<unix-seconds>,v1=<lowercase-hex>`. Consumers must
         *     reject `|now-t| > 300s` and use a constant-time compare.
         */
        WebhookSignatureHeader: string;
        /**
         * @description UUID v4 unique to this delivery attempt. Use it for idempotent
         *     processing; the same id may arrive more than once on retry.
         */
        WebhookIdHeader: string;
        /** @description The event type. Always equal to the `type` field of the body. */
        WebhookTypeHeader: "device.online" | "audio.finalized";
    };
    requestBodies: never;
    headers: {
        /**
         * @description Maximum number of requests the client may issue inside the current
         *     rate-limit window. Constant within a window.
         * @example 60
         */
        RateLimitLimit: number;
        /**
         * @description Requests still allowed in the current window. Decreases on each accepted
         *     request; resets to `X-RateLimit-Limit` when the window rolls over.
         * @example 42
         */
        RateLimitRemaining: number;
        /**
         * @description Unix timestamp (seconds since epoch, UTC) at which the current window
         *     rolls over and the quota resets.
         * @example 1748892900
         */
        RateLimitReset: number;
        /**
         * @description Seconds the client should wait before retrying. Always present on
         *     `429 Too Many Requests`.
         * @example 30
         */
        RetryAfter: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Service is degraded or unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every dependency is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ready"];
                };
            };
            /** @description At least one dependency is unhealthy. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ready"];
                };
            };
        };
    };
    registerDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceRegisterRequest"];
            };
        };
        responses: {
            /** @description Device registered (idempotent). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRegisterResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    syncDevice: {
        parameters: {
            query?: {
                /** @description ISO-8601 timestamp of the last successful sync. If omitted, a full snapshot is returned. */
                since?: string;
                /**
                 * @description Target device UUID. Ignored for `deviceHmac` callers (the device is
                 *     taken from the signature). **Required** for `userJwt` callers and
                 *     must reference a claimed device owned by the caller.
                 */
                device_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current sync payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSyncResponse"];
                };
            };
            /** @description Nothing changed since `since`. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    postDeviceEvents: {
        parameters: {
            query?: {
                /**
                 * @description Target device UUID. Ignored for `deviceHmac` callers (the device is
                 *     taken from the signature). **Required** for `userJwt` callers and
                 *     must reference a claimed device owned by the caller.
                 */
                device_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceEventsRequest"];
            };
        };
        responses: {
            /** @description Events accepted for processing. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor returned by a previous response. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of user accounts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description The caller is authenticated but is not an admin. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegisterRequest"];
            };
        };
        responses: {
            /**
             * @description Account created. Returns the new user's profile; no tokens are
             *     issued and the new account is not logged in.
             */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description The caller is authenticated but is not an admin. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Email already in use. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLoginRequest"];
            };
        };
        responses: {
            /** @description Authentication successful. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    refreshTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description New token pair issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed; a fresh token pair is issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            /** @description Missing token or `currentPassword` did not match. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listDevices: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor returned by a previous response. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated device list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    retireDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device retired. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated device. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    listDeviceEvents: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor returned by a previous response. */
                cursor?: components["parameters"]["Cursor"];
                /**
                 * @description Filter to a single event type (e.g. `card_unknown`). When omitted,
                 *     every event type is returned.
                 */
                type?: "card_scanned" | "card_unknown" | "playback_started" | "playback_finished" | "button_pressed" | "low_battery" | "error";
            };
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of device events, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceEventList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    claimDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceClaimRequest"];
            };
        };
        responses: {
            /** @description Device claimed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Device already claimed. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    listDeviceCards: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bindings (unpaginated; capped server-side). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardBindingList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    bindCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardBindingRequest"];
            };
        };
        responses: {
            /** @description Card binding upserted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardBinding"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    unbindCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device identifier (UUID). */
                id: components["parameters"]["DeviceId"];
                /** @description RFID UID in lowercase hex (no separators). */
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Binding removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listAudio: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor returned by a previous response. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createAudio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AudioCreateRequest"];
            };
        };
        responses: {
            /** @description Audio item created with upload URL. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioCreateResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getAudio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audio item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Audio"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteAudio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audio deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    finalizeAudio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Finalization accepted; transcoding queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Audio"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Audio already finalized. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getLatestFirmware: {
        parameters: {
            query: {
                /** @description Hardware revision (e.g. `r0`, `r1`). */
                hw_rev: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest manifest for the given hardware revision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FirmwareManifest"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description No firmware published for this hardware revision. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-service configuration status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description The caller is authenticated but is not an admin. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deviceOnlineWebhook: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description HMAC-SHA256 signature of `<t>.<raw-body>` using the per-user webhook
                 *     secret. Format `t=<unix-seconds>,v1=<lowercase-hex>`. Consumers must
                 *     reject `|now-t| > 300s` and use a constant-time compare.
                 */
                "Hush-Webhook-Signature": components["parameters"]["WebhookSignatureHeader"];
                /**
                 * @description UUID v4 unique to this delivery attempt. Use it for idempotent
                 *     processing; the same id may arrive more than once on retry.
                 */
                "Hush-Webhook-Id": components["parameters"]["WebhookIdHeader"];
                /** @description The event type. Always equal to the `type` field of the body. */
                "Hush-Webhook-Type": components["parameters"]["WebhookTypeHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookEnvelopeDeviceOnline"];
            };
        };
        responses: {
            /**
             * @description The consumer no longer wants this webhook. The backend will
             *     disable the subscription and stop retrying.
             */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Any 2xx status acknowledges receipt. The body is ignored. */
            "2XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    audioFinalizedWebhook: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description HMAC-SHA256 signature of `<t>.<raw-body>` using the per-user webhook
                 *     secret. Format `t=<unix-seconds>,v1=<lowercase-hex>`. Consumers must
                 *     reject `|now-t| > 300s` and use a constant-time compare.
                 */
                "Hush-Webhook-Signature": components["parameters"]["WebhookSignatureHeader"];
                /**
                 * @description UUID v4 unique to this delivery attempt. Use it for idempotent
                 *     processing; the same id may arrive more than once on retry.
                 */
                "Hush-Webhook-Id": components["parameters"]["WebhookIdHeader"];
                /** @description The event type. Always equal to the `type` field of the body. */
                "Hush-Webhook-Type": components["parameters"]["WebhookTypeHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookEnvelopeAudioFinalized"];
            };
        };
        responses: {
            /** @description Subscription is gone; stop retrying. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acknowledged. */
            "2XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
